name: Update README with recent GitHub commits

on:
  schedule:
    - cron: "0 18 * * 0"  # Every Sunday 11 PM PKT
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate recent commits section
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          config_output: svg

      - name: Commit changes
        run: |
          git config --global user.name 'maryamtufail01'
          git config --global user.email 'maryam.tufail190@gmail.com'
          git add metrics.svg
          git commit -m "Update metrics.svg with latest GitHub activity" || echo "No changes to commit"
          git pull --rebase origin main
          git push
