name: Update README with recent GitHub commits

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate recent commits section
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          config_output: svg

      - name: Embed generated SVG in README
        run: |
          sed -i '/<!--COMMITS-->/r metrics.svg' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'maryamtufail01'
          git config --global user.email 'maryamtufail190@gmail.com'
          git add README.md
          git commit -m "Update README with latest commits" || echo "No changes to commit"
          git push
